config/routes.rb
Rails.application.routes.draw do
  get "/auth/:provider/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", :as => :signout
  root to: 'pages#home'
  resources :ideas

end

app/models/idea.rb
require './lib/assets/scripts/PhotoSearch'
class Idea < ActiveRecord::Base
	before_save do 
		if self.image_url.blank? || title_changed?
			self.image_url = FlickrFinder.new.find_image(self.title)
		end
	end

	def validate_each(record, attribute, value)
    begin
    	puts "&&&&&&&&&&&&&&&&&& each attribute #{attribute}"
    	if attribute == 'image_url'
    		puts "######################## validate image_url #{value}"
    		uri = URI.parse(value)
      		resp = uri.kind_of?(URI::HTTP)
      		puts "&&&&&&&&&&&&&&&&&& Seems like a invalid url. lets get a new url &&&&&&&&&&&&&&&&&&"
      		if resp == false
      			puts "&&&&&&&&&&&&&&&&&& Seems like a invalid url. lets get a new url &&&&&&&&&&&&&&&&&&"
      			value = FlickrFinder.new.find_image(self.title)
      		end
    	end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
	def self.create_with_omniauth(auth)
	  create! do |user|
    	user.provider = auth["provider"]
    	user.uid = auth["uid"]
    	user.name = auth["info"]["name"]
  	  end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

  def index
    @query = params[:query]
    if @query.blank?
      @ideas = Idea.all;
    else
      # @ideas = Idea.where(title: @query)
      @ideas = Idea.where('title like ?', "%#{@query}%")
    end
    render 'index'
  end

  def show
    @idea = Idea.find(params[:id])
    render 'show'
  end

  def new
    @idea = Idea.new
    render 'new'
  end

  def edit
    @idea = Idea.find(params[:id])
    render 'edit'
  end

  def create
    @idea = Idea.new(idea_params)

    if @idea.save
      redirect_to @idea, notice: 'Idea was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    @idea = Idea.find(params[:id])
    if @idea.update(idea_params)
      redirect_to @idea, notice: 'Idea was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy
    redirect_to ideas_url, notice: 'Idea was successfully destroyed.'
  end

  private
  # Only allow a trusted parameter "white list" through.
  def idea_params
    params.require(:idea).permit(:title, :description, :image_url)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
  	auth = request.env["omniauth.auth"]
  	user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
  	session[:user_id] = user.id
  	redirect_to root_url, :notice => "Signed in!"
  end

  def destroy
  	session[:user_id] = nil
   	redirect_to root_url, :notice => "Signed out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ideas/_form.html.erb
<%= form_for(@idea) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<div class="page-header">
  <h1>Ideas<small> ...change the world</small></h1>
</div>

<ul class="list-group">
<% @ideas.each do |idea| %>
  <li class="list-group-item">
        <%= image_tag(idea.image_url, class: 'img-thumbnail')%>
        <div>
          <h4><%= idea.title %></h4>
          <%= idea.description %>
        </div>
        <div class="btn-group btn-group-sm">
          <%= link_to 'Show', idea, class: "btn btn-info" %>
          <%= link_to 'Edit', edit_idea_path(idea), class: "btn btn-warning" %>
          <%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        </div>
        <small><%= time_ago_in_words(idea.updated_at) %></small>
        <p class="badge"> comments: <span>0</span></p>
  </li>
<% end %>  
</ul>

<!-- <table class="table table-striped"> -->
  <!-- <thead>
    <tr>
      <ul class="pagination">
      <li class="disabled"><a href="#">&laquo;</a></li>
      <li class="active"><a href="#">1 <span class="sr-only">(current)</span></a></li>

      <th>Title</th>
      <th>Description</th>
      <th>Image url</th>
      <th colspan="3"></th>
      </ul>
    </tr>
  </thead> -->

<!--   <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= image_tag(idea.image_url, class: 'img-thumbnail')%></td>
        <td><%= idea.title %></td>
        <td><%= idea.description %></td>
        <td><%= time_ago_in_words(idea.updated_at) %></td>
        <td><%= link_to 'Show', idea %></td>
        <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
        <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody> -->
<!-- </table> -->

app/views/ideas/new.html.erb
<h1>New idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @idea.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @idea.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @idea.image_url %>
</p>

<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
  		<title>Ideation</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<nav class="navbar navbar-default" role="navigation">
		  <div class="container-fluid">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <a class="navbar-brand" href="/">INV Ideas</a>
		    </div>

		    <!-- Collect the nav links, forms, and other content for toggling -->
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		      <ul class="nav navbar-nav">
		        <li><%= link_to 'All Ideas', ideas_path %></li>
		        <li><%= link_to 'New Idea', new_idea_path %></li>
		      </ul>
		      <ul class="nav navbar-nav navbar-right">
		        <%= form_for ideas_path, method: 'get', html: {class: "navbar-form navbar-left"} do %>
		      	<div class="form-group">
		      		<%= search_field_tag :query, @query, class: 'form-control' %>
		      		<button type="submit" class="btn btn-default btn-md">
  					<span class="glyphicon glyphicon-search"></span>
					</button>
		        </div>
				<% end %>
		      </ul>
		    </div><!-- /.navbar-collapse -->
		  </div><!-- /.container-fluid -->
		</nav>
		
		<div class='container'>
    		<%= yield %>
		</div>
	</body>

</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<p> This is a static page... how did you get here?</p>

app/views/session/create.html.erb
<h1>Session#create</h1>
<p>Find me in app/views/session/create.html.erb</p>